<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $guarded = [];
//    protected $fillable = ['title', 'excerpt', 'body'];

//    /**
//     * @return string
//     */
//    public function getRouteKeyName() // in the case you need MANY slugs, use this method
//    {
//        return 'slug'; // TODO: Change the autogenerated stub
//    }


}